{% set name = "pygobject-stubs" %}
{% set version = "2.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygobject_stubs-{{ version }}.tar.gz
  sha256: d2d89997c618819e8aecd67a3680bebbbb6349121f0b0452204dbdd7e157ad43

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65.0.0
    - pip
  run:
    - python >={{ python_min }}

test:
  commands:
    - pip check
    - pip show pygobject-stubs
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/pygobject/pygobject-stubs
  summary: Typing stubs for PyGObject
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilkClouds
